Add xapi video verbs
uhm-coe/h5p-video pull request #1
Opened 2018-03-14 19:51 UTC by otacke

Hey everyone!

I started to push some things around as I suggested to do, and there's still some more that I will move from the handlers to video.js, but I may not have time for that before next week. Then, I'll also have a look at the segment timing issue.

We could switch roles now, and you could have a look if I broke something :-) And maybe you'll find some time to look at the bug that I pointed at.

Best,
Oliver

2018-03-14 20:15 UTC, figureone commented
Thanks Oliver! I should be back on it today; sorry for my absence, last Friday we had a server intrusion and I've been dealing with that postmortem since. 

Last Friday I was halfway through a fix for the bug you found, so I should have something for that as well.

2018-03-15 00:14 UTC, figureone requested changes
Looks good so far! Only real issue is the munging of some of the verb ID (URL) in the refactored `getArgsXAPI()` (some Video Profile verbs use adlnet.gov, some use w3id.org).

Should be ready to merge these changes into the larger pull request when you finish moving things out of html5.js/youtube.js and into video.js. I'll solve the conflict I mentioned about `xAPIBase` and `xAPIObject` when I do that merge.

2018-03-15 00:14 UTC, figureone commented on scripts/x-api.js
> +          'id': 'http://adlnet.gov/expapi/verbs/' + params.verb,
Some verbs in the Video Profile spec use a different URL (w3id.org instead of adlnet.gov), so we can't just prefix "http://adnlet.giv/expapi/verbs/":
```
http://adlnet.gov/expapi/verbs/initialized
https://w3id.org/xapi/video/verbs/played
https://w3id.org/xapi/video/verbs/paused
https://w3id.org/xapi/video/verbs/seeked
http://adlnet.gov/expapi/verbs/interacted
http://adlnet.gov/expapi/verbs/completed
http://adlnet.gov/expapi/verbs/terminated
```
https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html#23-verbs

2018-03-15 00:14 UTC, figureone commented on scripts/x-api.js
> +    var xAPIBase;
Oops, I committed a conflicting version of this here: https://github.com/h5p/h5p-video/pull/17/commits/6c0dbf9a4f22c99b4d9a363eb09552e37737af46

When I merge, I'll use my variable naming (`xAPIObject` instead of `xAPIBase`), and keep your comparison against `undefined` instead of `null`.

2018-03-15 00:14 UTC, figureone commented on scripts/html5.js
> -      // @todo: Not currently used.
Not sure if we should keep these todo marks; Kirk put them there as hints about what the specific player did not implement. In this case, the html5 player doesn't fire a fullscreen event when it goes fullscreen.

2018-03-15 00:14 UTC, figureone commented on scripts/youtube.js
> -      // @todo: Not currently used.
Not sure if we should keep these todo marks; Kirk put them there as hints about what the specific player did not implement. In this case, the youtube player doesn't fire a volumechange event when the volume is changed.

2018-03-15 00:14 UTC, figureone commented on scripts/youtube.js
> -      // @todo: Not currently used.
Not sure if we should keep these todo marks; Kirk put them there as hints about what the specific player did not implement. In this case, the youtube player doesn't fire a fullscreen event when it goes fullscreen.

2018-03-15 00:15 UTC, figureone reviewed
👍

2018-03-18 15:12 UTC, otacke commented
Missing the different verbs was really a dumb mistake. Thanks for cathing this!
I usually clean up TODOs in the final stages, so I wouldn't mind to keep them in for now.

2018-03-23 19:45 UTC, merged